[package]
name = "mermaid-ascii"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5.4", features = ["derive"] }
env_logger = "0.11"
indexmap = "2.2"
log = "0.4"
once_cell = "1.19"
regex = "1.10"
thiserror = "1.0"

[dev-dependencies]
assert_cmd = "2.0"
